name: run flyte workflow

on:
  workflow_call:
    inputs:
      workflow_directory:
        required: true
        type: string
      workflow_file:
        required: true
        type: string
      workflow_name:
        required: true
        type: string
    secrets:
      UNION_API_KEY:
        required: true

jobs:
  register-and-run-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ format('{0}-pip-{1}', runner.os, hashFiles('dev-requirements.in', 'requirements.in')) }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Register the workflows
      working-directory: ${{ inputs.workflow_directory }}
      env:
        UNION_API_KEY: ${{ secrets.UNION_API_KEY }}
      run: |
        union run --remote ${{ inputs.workflow_file }} ${{ inputs.workflow_name }}

