name: Run all examples

on:
  push:
  pull_request:
    paths:
      - "user_guide/**"
      - "tutorials/**"
  workflow_dispatch:  # Enables manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  hello_world:
    uses: unionai/unionai-examples/.github/workflows/reusable_flyte_wf.yml@run-ci
    with:
      workflow_directory: user_guide/core_concepts/actors/serverless
      workflow_file: hello_world.py
      workflow_name: wf
    secrets:
      UNION_API_KEY: ${{ secrets.UNION_API_KEY }}
  multiple_tasks:
    uses: unionai/unionai-examples/.github/workflows/reusable_flyte_wf.yml@run-ci
    with:
      workflow_directory: user_guide/core_concepts/actors/serverless
      workflow_file: multiple_tasks.py
      workflow_name: my_parent_wf
    secrets:
      UNION_API_KEY: ${{ secrets.UNION_API_KEY }}
  plus_one:
    uses: unionai/unionai-examples/.github/workflows/reusable_flyte_wf.yml@run-ci
    with:
      workflow_directory: user_guide/core_concepts/actors/serverless
      workflow_file: plus_one.py
      workflow_name: wf
    secrets:
      UNION_API_KEY: ${{ secrets.UNION_API_KEY }}
  pod_template:
    uses: unionai/unionai-examples/.github/workflows/reusable_flyte_wf.yml@run-ci
    with:
      workflow_directory: user_guide/core_concepts/actors
      workflow_file: pod_template.py
      workflow_name: wf
    secrets:
      UNION_API_KEY: ${{ secrets.UNION_API_KEY }}
  basic:
    uses: unionai/unionai-examples/.github/workflows/reusable_flyte_wf.yml@run-ci
    with:
      workflow_directory: user_guide/core_concepts/artifacts
      workflow_file: basic.py
      workflow_name: wf
    secrets:
      UNION_API_KEY: ${{ secrets.UNION_API_KEY }}
  model_caad:
    uses: unionai/unionai-examples/.github/workflows/reusable_flyte_wf.yml@run-ci
    with:
      workflow_directory: user_guide/core_concepts/artifacts
      workflow_file: model_card.py
      workflow_name: wf
    secrets:
      UNION_API_KEY: ${{ secrets.UNION_API_KEY }}
  partition_keys_input:
    uses: unionai/unionai-examples/.github/workflows/reusable_flyte_wf.yml@run-ci
    with:
      workflow_directory: user_guide/core_concepts/artifacts
      workflow_file: partition_keys_input.py
      workflow_name: wf
    secrets:
      UNION_API_KEY: ${{ secrets.UNION_API_KEY }}
